### ISSUE TITLE
Use Pool to ensure thread safety

### ISSUE THREAD

**Issue by chen990627** [EsotericSoftware/kryo#1147]
1.What is the typical setting for the maximumCapacity property of the Kryo object pool?
2.What is the typical setting for the maximumCapacity property of the Output object pool?
3.What is the typical setting for the maximumCapacity property of the Input object pool?
![image](https://github.com/user-attachments/assets/6bd7e6cc-c9ee-4302-89c8-c0910e1d52e7)

**Comment by theigl** [comment]
As all pool sizing, this depends on your use-case:

- How many threads are using Kryo concurrently? 
- How many of those threads are usually doing serialization vs deserialisation?
- Are you OK with threads blocking and waiting for a Kryo instance to become available or do you want to make the pool large enough so that normally all threads can get an instance without blocking?
- ....
