### ISSUE TITLE
Feature request: refuse to serialize instances which cannot be deserialized

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#313]
A common issue we're seeing is that a class will be serialized by Kryo and stored in a file, but then on recovery it fails to deserialize for one reason or another (an exception of some sort). Ideally we could ask Kryo to refuse to serialize instances which will fail to deserializable, because otherwise we're writing a bomb inside the file which will explode much later, when the process is bounced and we try to read from it. I've been tempted to add a check inside our kryo wrapper that would only be enabled in test/qa which, right after bytes are written, would try to create an instance from those bytes and verify there is no exception. It would make test/qa a bit slower, but the risk prevention would be worth it.

Have you thought about this before?

**Comment by romix** [comment]
The idea of trying to deserialize the object that was just serialized is neat. It can be useful for test/qa. It may catch some bugs. 

But I think most of the issues related to deserialization are due to the fact that the configuration used at the time of deserialization is usually different from the one used during serialization, e.g. a different version of Kryo lib is used, Kryo instances are configured in a different way, definitions of serialized classes have changed, different class-loaders are used, etc. Using your proposed approach in such situations is not likely to help as it is not quite clear how to model those "differences" in configuration.
