### ISSUE TITLE
Is there an easy way to partially deserialize an object through the API?

### ISSUE THREAD

**Issue by toni-l-d** [EsotericSoftware/kryo#324]
Hi,

To partially deserialize an object (say, some fields instead of the whole thing), how can it be done through the framework?

Both partial and full serialization are needed in this case (partial to check if some field corresponds to a certain value; if it does, then it proceeds to deserialize the large object). The documentation mentions something about using Kryo for nested objects - in such a case, besides retrieving the nested object, does the framework avoid deserializing all the remaining info?

Thanks and regards

**Comment by NathanSweet** [comment]
This is an issue tracker. Please using the mailing list for questions.

If you control what order the fields are serialized, you could deserialize just the fields you want first. If you only need to do this for the root object that is fine, otherwise the problem is how to skip the rest of the bytes so the next object can be deserialized?

**Comment by toni-l-d** [comment]
Yes that's the point, when using the default FieldSerializer for the root object and everything else in the object's graph, how to get only to the nested object/field you're interested in, (I suppose the Input object would be the way to do it). So starting from a root object, what's the sequence?

- Reading some class information (id)
- Reading a byte with the field's size
- Reading the field

The way the information is laid out when serializing depends on a few options taken (for instance, whether the class is registered or not, whether there are cycling references, etc.). So my original question is whether there's an API mechanism (through Kryo or Input) to abstract these implementation details and get right to the field you need, or whether you need to do it 'manually'.

**Comment by NathanSweet** [comment]
There's no magic to jump into the middle of some bytes and deserialize only a part. There is no knowledge about where one object starts and where another ends. Or to be more accurate, that knowledge is baked into the Java code that does deserialization. You could deserialize all the objects before the one you care about and discard the bytes. Or, you can use a serializer that first writes the number of bytes for an object, then the object bytes. This way you know the length of each object as you deserialize and can skip objects you don't care about. Of course, the penalty is buffering the bytes so you can write the length first. See CompatibleFieldSerializer which uses chunked encoding to do this for each field, allowing fields that don't have corresponding class files to be skipped.

**Comment by bitdivine** [comment]
@NathanSweet If done manually, you can even skip the per-object length field most of the time because performant data structures are very often fixed length, so if you have an array of n things, you can jump to the ith pretty easily.  The serialisation with this pattern will typically group all objects of a given type together and then there will be a header saying:  124 objects of type A starting at this offset, 74 of type B starting at that offset,  ...  The reader then reads the header and knows exactly which address to look at to get the object it needs.  If the query is for a nested object that means that locality is poor but the payoff is that little data is read.

**Comment by NathanSweet** [comment]
You can read only the minimum needed to skip bytes and can make assumptions about the data, but this is very brittle. Any changes to the serialization code can break this. The safest thing is to read the objects and discard them.
