### ISSUE TITLE
references are enabled by default?

### ISSUE THREAD

**Issue by tianshouzhi** [EsotericSoftware/kryo#617]
the document mentioned "By default references are not enabled"，but when I test with 5.0.0-RC1，I found Kryo.getReferences() return true.

**Comment by NathanSweet** [comment]
You're right. This happens because a ReferenceResolver is provided by default, which then enables references. The docs say it is disabled by default, `setReferences` javadoc says "Default is true.". Who to believe?! We can decide either way. I think it makes sense for the defaults to have most features disabled, especially those which add overhead, as references do. Any naysayers should speak now! In the meantime, I'll wait for [Eclipse to be able to run unit tests again](https://bugs.eclipse.org/bugs/show_bug.cgi?id=538433).

**Comment by isaki** [comment]
I vote that references be disabled by default; I agree that the defaults should be as barebones as possible and developers/users should opt into features (and thus be aware of what overhead they are incurring).

**Comment by magro** [comment]
@NathanSweet should this be resolved before the next release?
