### ISSUE TITLE
Kryo IndexOutOfBoundsException: Index: 113, Size: 5

### ISSUE THREAD

**Issue by Maatary** [EsotericSoftware/kryo#623]
I am using Kryo 5.0.0-RC1. I have the following exception:

java.lang.IndexOutOfBoundsException: Index: 113, Size: 5 at java.util.ArrayList.rangeCheck(ArrayList.java:657) at java.util.ArrayList.get(ArrayList.java:433) at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)

I have seen those exceptions in many places with past version of Kryo and was not expecting it in this version, as most of the solution seem to have been addressed in this version e.g. flushing output and so on.

In my case this is happening at readying time.

From what i understand it is rather difficult to spot on. But those who know Kryo, what does the exception means, so i can start fetching the problem. When in the code of Kryo this exception is being raised, and what is the meaning of it.

Just for the record, in my case it is very strange. The exception only happen after a while. I have a data pipeline, where I use akka-stream to fetch some data, pass them trough kafka, and then process them in kryo. Everything works fine, until I reach 1,199,541 of records and a bit more processed. It always happen around that same number of records processed.

Any idea or hint for me to look at.

Akka-Stream

.mapAsyncUnordered(8){value =>
      Future{
        val kryo = kryoPool.obtain()
        val outStream = new ByteArrayOutputStream()
        val output = new Output(outStream, 4096)
        kryo.writeClassAndObject(output, value)
        output.close()
        kryoPool.free(kryo)
        new ProducerRecord[String, Array[Byte]]("NormalizedRawData", outStream.toByteArray)
        }
      }
      .runWith(Producer.plainSink(producerSettings))
Spark Init

    object KryoContext {
        lazy val kryoPool = new Pool[Kryo](true, false, 16) {
          protected def create(): Kryo = {
            val cl = Thread.currentThread().getContextClassLoader()
            val kryo = new Kryo()
            kryo.setClassLoader(cl)
            kryo.setRegistrationRequired(false)
            kryo.addDefaultSerializer(classOf[scala.collection.Map[_,_]], classOf[ScalaImmutableAbstractMapSerializer])
            kryo.addDefaultSerializer(classOf[scala.collection.generic.MapFactory[scala.collection.Map]], classOf[ScalaImmutableAbstractMapSerializer])
            kryo.addDefaultSerializer(classOf[RawData], classOf[ScalaProductSerializer])
            kryo
          }
        }

        lazy val outputPool = new Pool[Output](true, false, 16) {
          protected def create: Output = new Output(4096)
        }

        lazy val inputPool = new Pool[Input](true, false, 16) {
          protected def create: Input = new Input(4096)
        }
}
Spark Usage

   def decodeData(rowOfBinaryList: List[Row], kryoPool: Pool[Kryo], inputPool: Pool[Input]): List[RawData] = {

    val kryo = kryoPool.obtain()
    val input = inputPool.obtain()
    val data = rowOfBinaryList.map(r => r.getAs[Array[Byte]]("message")).map{ binaryMsg =>
      input.setInputStream(new ByteArrayInputStream(binaryMsg))
      val value = kryo.readClassAndObject(input).asInstanceOf[RawData]
      input.close()
      value
    }
    kryoPool.free(kryo)
    data
}
If you have any hint whatsoever that may help please just suggest anything.

**Comment by NathanSweet** [comment]
The first time an object is encountered in an object graph that is being serialized, an int ordinal is written. This is the "reference id". See ReferenceResolver `addWrittenObject` and where that is used.

When deserialized, before reading an object, a reference id is read. See Kryo `readRefereneOrNull`. The first time an object is encountered, it is stored using ReferenceResolver `setReadObject` (in Kryo `reference`). The next time that object is encountered, in the bytes there is only the reference id. ReferenceResolver `getReadObject` is passed the id to get the object that was previously encountered.

The error you are seeing is that ReferenceResolver `getReadObject` is passed an id that is higher than the number of objects encountered. This likely means that the deserialization of a previous object was incorrect, eg it read too many or not enough bytes, then when Kryo reads the reference id, the bytes it is reading are completely wrong. This kind of deserialization error is common: something explodes because some earlier read the wrong number of bytes. There are no limits to how it can explode, eg if the reference id happened to be read as a lower number, it would be a valid object, then you might get a class cast exception when that object is assigned to a field, etc.

Typically you need to isolate the objects that are failing, turn on logging when you serialize, then turn on logging and deserialize, then compare the logs to see where the wrong number of bytes were read. I suggest trying to reduce the problem to Java code that only uses Kryo and that fails every time, then I can be of more help. I'll close this issue now, but we can continue discussion here and I'll reopen the issue if we can show it is a Kryo problem.

**Comment by pratheek017** [comment]
@NathanSweet I did try your suggestion of isolating the failing object and check the number of bytes being written and read. They are equal. I digged deep into the failing object to see the order of serialization and deserialization too. I've checked it 10 times and it's fine. I still have this indexOutOfBoundsException.
