### ISSUE TITLE
Why kryo cannot serialize scala HashMap

### ISSUE THREAD

**Issue by deshanxiao** [EsotericSoftware/kryo#625]
I try to serialize the scala class mutable.HashMap,but it is empty when deserialized
I know that maybe I need to use some third party libs like chill.
And I notice that Kryo can process most class of Java in kryo document.So Can you tell me which classes cannot be serialized? And why? Thanks!

**Comment by magro** [comment]
It's not possible to provide a complete list of classes that kryo cannot serialize.
Kryo understands itself as a serialization toolkit that allows you to write your own serializers. It comes with a reflection based general purpose serializer (FieldSerializer) which does its best to support as many as possible cases, but for some kinds of classes it might just not work. That kryo ships with specialized/optimized serializers for some standard java classes is for convenience so that not everybody has to write his own serializer for e.g. a java List or DateTime. For classes that are not part of the jre there are other libraries like kryo-serializers or chill.

So for standard scala classes you definitely should use s.th. like chill.
