### ISSUE TITLE
Preferred way of extending serializers?

### ISSUE THREAD

**Issue by tschuchortdev** [EsotericSoftware/kryo#639]
What is the preferred way of extending serializers? Say I have a class `B` that extends `A` and `B` has additional fields that need to be serialized. Obviously I don't want to write all the serialization logic for the fields inherited from `A` again.

Currently I'm doing it by creating an instance of the `ASerializer` and then calling `read` and `write` directly, but it's not working. I'm always getting garbage back like totally unrelated classes (for example `Kryo` itself or some other serializer)  or `null` when my `read` method never returns `null`. I'm not sure if it's due to my composed serializers or some other issues.

```kotlin
class ASerializer : Serializer<A> {
  fun write(kryo: Kryo, out: Output, obj: A) {
      kryo.writeClassAndObject(out, obj.aField)
  }

  fun read(kryo: Kryo, in: Input, clazz: Class<out A>): A {
    val aField = kryo.readClassAndObject(in)

    return object : A {
        val aField = aField
    }
  }
}

class BSerializer : Serializer<B> {
  private val aSerializer = ASerializer()
  fun write(kryo: Kryo, out: Output, obj: B) {
      aSerializer.write(kryo, out, obj)
      kryo.writeClassAndObject(out, obj.bField)
  }

  fun read(kryo: Kryo, in: Input, clazz: Class<out B>): B {
    val a = aSerializer.read(kryo, in, clazz)
    val bField = kryo.readClassAndObject(in)

    return object : B, A {
        val aField = a.aField
        val bField = bField
    }
  }
}
```

**Comment by NathanSweet** [comment]
The mailing list is better for questions/discussion, but I'll answer here this time.

You can use either inheritance or composition. Often for composition you would use Kryo methods and pass the serializer. Eg see these links:
https://github.com/EsotericSoftware/kryo#nested-serializers
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/CollectionSerializer.java#L148-L154

When you are serializing part of an object with a serializer using composition, as in your example, then you can call the read/write serializer methods directly, since you don't need Kryo to handle null, references, etc. That stuff is already done for the object being serialized, no need to do it again.

As to why you are having problems, I can't say. Enable trace logging (`Log.TRACE();`) and compare writing to reading -- something must not match up. If you provide code, please provide Java.

**Comment by tschuchortdev** [comment]
A significant problem with composition that I ran into is that all the objects serialized by the super-class serializer (`ASerializer` in this example) will reference the `A` instance when there are cyclic references instead of the `B` instance. I haven't found a satisfying solution for that yet, but moved to a completely different approach.

**Comment by NathanSweet** [comment]
Some serializers provide a `create` method that can be overridden, allowing you to use an `A` serializer where `read` returns a `B` instance, though this can be a bit clunky.

Maybe the `A` serializer could provide a method that takes an `A` instance and only reads the fields, without doing generics, creating an instance, or storing a reference. I wonder if all the serializers should provide such a method?
