### ISSUE TITLE
ConcurrentSkipListMap w/o Comparator

### ISSUE THREAD

**Issue by andre-paris** [EsotericSoftware/kryo#660]
Kryo doesn't serialize the `ConcurrentSkipListMap` comparator.
Tested with version 4.0.2
How to reproduce:
```java
        Kryo kryo = new Kryo();
        ConcurrentSkipListMap<String, Object> map = new ConcurrentSkipListMap<>(Comparator.reverseOrder());
        System.out.println("comparator=" + map.comparator());

        try (OutputStream stream = Files.newOutputStream(Paths.get("/tmp/map"));
             Output output = new Output(stream)) {
            kryo.writeClassAndObject(output, map);
        }

        try (InputStream stream = Files.newInputStream(Paths.get("/tmp/map"));
             Input input = new Input(stream)) {
            Object o = kryo.readClassAndObject(input);
            System.out.println("comparator=" + ((ConcurrentSkipListMap) o).comparator()); // Ops!!
        }
```

**Comment by NathanSweet** [comment]
Every class that will be serialized by Kryo must be carefully evaluated. Serializers are provided for many JRE classes, but Kryo doesn't claim to support them all. In some cases it is not possible because the necessary API is not available. Otherwise we are willing to include serializers in the list of [default serializers](https://github.com/EsotericSoftware/kryo/#default-serializers) for JRE classes, as long as they don't rely on private API. If it can't be done with public API, you can make the serializer available in the [kryo-serializers](https://github.com/magro/kryo-serializers) project.

If you'd like to submit a PR for the ConcurrentSkipListMap comparator that works with public API, we'd merge it!
