### ISSUE TITLE
pool concurrency problem?

### ISSUE THREAD

**Issue by HiwayChe** [EsotericSoftware/kryo#664]
![image](https://user-images.githubusercontent.com/5837440/54834519-4cc51f00-4cfb-11e9-8189-3b6b098a29d8.png)

I see the above code in https://github.com/EsotericSoftware/kryo/commit/4db5a3c57b323e1fef6ea853c99f3996a9b120b0,
I wonder should `reset(object)` place before `offer(object)`, if one thread just `offer` object to pool, another thread immediately `obtain` it, and `reset(object)` has not been executed, does it may cause a concurrency problem?

**Comment by magro** [comment]
Good catch! Do you want to submit a PR?

**Comment by HiwayChe** [comment]
No, you do it, it is just a small change.

**Comment by magro** [comment]
I don't know why you don't want to submit a PR (it's a small change as you say), and I don't know why you expect me to do it.

Because you don't pay anything for this piece of software, you cannot expect from anybody to do anything for you.
IMHO OSS lives from contributions. OSS gives you the freedom to improve things that were provided by others on your own - which is a really great thing! 

I personally used kryo some years ago and since then try to support it here and there. I do this because I believe in OSS. 

I don't expect that you fix the issue you discovered. But reading your words "you do it" makes me sad. Instead, you could have asked me if I could do it, this would be a totally different story. Please try to be nice in this (OSS) world.

**Comment by isaki** [comment]
It could be a language thing; given the user's profile English is not likely his/her primary tongue and as such, may not have known the connotative difference between "you do it" vs "you can do it", the former being a tad rude to a native English speaker and the latter deferring to you. I read their statement to imply the latter rather than the former.

I could be wrong, of course. I'm just offering an alternative viewpoint in the hopes it makes you feel a bit better.

**Comment by harrybtlin** [comment]
English is not his native language

**Comment by magro** [comment]
Thanks for the alternative viewpoint.

**Comment by HiwayChe** [comment]
> Thanks for the alternative viewpoint.

Sorry, I don't mean to offend you, as english is not my first language, I'll try to improve my english.

**Comment by HiwayChe** [comment]
..., emm, just close this issue by misoperation, reopen it.

**Comment by julien-may** [comment]
What's the state here? If no one's doing it, I am glad to do the fix.

**Comment by magro** [comment]
@julien-may great if you'd take care of it.

**Comment by julien-may** [comment]
here you go: https://github.com/EsotericSoftware/kryo/pull/665

**Comment by magro** [comment]
Thanks!

**Comment by julien-may** [comment]
@magro: may i ask when you suppose to release RC3?

**Comment by magro** [comment]
@julien-may kryo-5.0.0-RC3 is just on its way to maven central. Thanks for your patience! :-)
