### ISSUE TITLE
kryo Encountered unregistered class ID:97

### ISSUE THREAD

**Issue by zgj12138** [EsotericSoftware/kryo#669]
hello, I met a problem when using kryo. I used kryo-shaded of version 3.0.3 to serialized a class, and I deserialized  it with 4.0.0 version. It through an exception 'kryo Encountered unregistered class ID:97'. How can I solve it ?

**Comment by MarcMil** [comment]
You might need to register the classes you serialize and deserialize beforehand in the same way. When registering a class, kryo by default assigns an unique number to each class incrementally. This id is used to reference the type in the serialized binary.

See https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.0 for the compatibility between Kryo 3 and 4.
Also it is a good idea to check what happens if you use the same version of kryo to see whether it could be related to incompatibilities between different kryo versions.

Generally, having a piece of code might help the community to help you with your problem.

**Comment by magro** [comment]
Closed for now, please reopen if this issue still exists.

**Comment by DhananjayAshok** [comment]
I'm having the same issue

**Comment by Castile** [comment]
I'm having the same issue， but I indeed regist this class，what reason else？
