### ISSUE TITLE
Selectively enable chunked encoding for fields in TaggedFieldSerializer

### ISSUE THREAD

**Issue by mani1996** [EsotericSoftware/kryo#730]
Hi,
I'm working on a project that uses Kryo-4.0.2. TaggedFieldSerializer in this version supports the "annexed" label, which allows selectively enabling chunked encoding for fields

Since chunked encoding results in both size and performance impact, I was thinking of have a workflow that 
1. Marks new fields as "annexed" when introduced, for compatibility reasons 
2. The "annexed" fields are cleaned up (remove the "annexed" label) at regular intervals to avoid overhead due to chunk metadata (say, once in 2 weeks)

I see that the "annexed" label has replaced in favour of a global "chunkedEncoding" config, which prevents workflows like the one I've mentioned above

Marking "chunkedEncoding" as true globally writes all fields in Chunked encoding format, which has a high size and performance cost

Can I know the reasoning behind dropping the "annexed" label? Are there any plans to restore it, going forward?

Thanks in advance!

**Comment by theigl** [comment]
I don't know why this was removed but here is the commit that removed field-level support: https://github.com/EsotericSoftware/kryo/commit/a532b110ddf38efe2d6a1a8b56153d7bbf403542

I'm guessing it was removed to simplify the code in `TaggedFieldSerializer` or fix some issue caused by it.

Maybe @NathanSweet can shed some light on this.
