### ISSUE TITLE
Could the writeString(CharSequence) method be back in com.esotericsoftware.kryo.io.Output?

### ISSUE THREAD

**Issue by pgrt** [EsotericSoftware/kryo#832]
Dear kryo maintainers,

I am working on the Debian packaging of several software, and while I need to update the Debian-packaged version of kryo to a recent version in order to package nextflow, I see that gradle also depends on kryo and uses the writeString(CharSequence) method from com.esotericsoftware.kryo.io.Output. I can see this method disappeared between versions 4 and 5 of kryo.

If possible, I would greatly appreciate the writeString(CharSequence) back in the Output class. This would (among others) benefit current and future versions of gradle, which I think is important.

As an alternative, could you provide me with a possible implementation of writeString(CharSequence) please?

Thanks a lot for your attention,
Pierre Gruet

P.S.: As a side note, I would completely understand if you did not want to have the method back in Output.java -- obviously you had some good reason to remove it. And also maybe gradle developers should adapt their code to your new ABI if they need it: I also see the method total() of Output now returns a long instead of an int... perhaps there are other such changes that are not easy to backport.

**Comment by theigl** [comment]
@pgrt: There were quite a lot of breaking changes between Kryo 4 and Kryo 5. Not only in the public API, but also in the binary representation of serialized data. So even if you'd manage to compile Gradle against Kryo 5, reading previously persisted data would most likely fail.

> And also maybe gradle developers should adapt their code to your new ABI if they need it

Yes, this would be the way to go. Moving to Kryo 5 has to be a deliberate decision, because the binary format is not compatible and there have to be appropriate migrations in place.

**Comment by pgrt** [comment]
Hi,

Thanks a lot for those explanations, all this sounds sensible to me! That's fine.

Thus I'm closing the issue.

Thanks again,
Pierre
