### ISSUE TITLE
Minification breaks compatibility

### ISSUE THREAD

**Issue by Erhannis** [EsotericSoftware/kryo#853]
**Describe the bug**
This is not very surprising, once you realize the problem, but minifying your code causes Kryo to serialize objects differently than non-minified code, meaning minified code cannot deserialize (some) objects serialized by non-minified code, and vice-versa.  (Gives errors like "Unable to resolve reference for String with id: 15" and "IndexOutOfBoundsException: Invalid index 15, size is 1".)

Is there a way to permit minification while retaining compatibility with non-minified code?  In particular, I'm minifying an Android app with whatever the default minification strategy is.

**To Reproduce**
Instantiate some custom object and serialize it.  For example:
```
    public class Thing {
        public String str;
        public int i;
        public Object obj;
        public HashMap<String, String> map;

        public Thing(String str, int i, Object obj, HashMap<String, String> map) {
            this.str = str;
            this.i = i;
            this.obj = obj;
            this.map = map;
        }

        private Thing() {
        }
    }
```

Run the code on Android, save/log the resulting bytes.  (In my tests, you can also run it on a desktop and it gives the same result.)
Minify the app and run it again, and compare the resulting bytes.  Observe that they are different.  (Or, try to deserialize one output with the opposing code.)

**Environment:**
 - OS: Android 6.0.1
 - JDK Version: ?
 - Kryo Version: 5.2.0

**Comment by theigl** [comment]
@Erhannis: I have no experience with Android development and no time to look into this in detail. Is there any way you could reproduce this in a test-case that doesn't require Android? 

What does minification actually do? Does it compact the field and class names? Could you disassemble the minified class and create a roundtrip serialization test with your minified and unminified classes? See [this gist](https://gist.github.com/theigl/9bdbd7e97113bc5c230ceb96f79367ad) for an example of such a test. Instead of adding and removing fields, you could swap out the whole test class for the minified version.

**Comment by theigl** [comment]
The simplest solution would probably be to exclude classes you want to serialize with Kryo from minification/obfuscation.

To quote the [Android docs](https://developer.android.com/studio/build/shrink-code#obfuscate):

> Additionally, if your code relies on predictable naming for your app’s methods and classes—**when using reflection**, for example, you should treat those signatures as entry points and specify keep rules for them, as described in the section about how to customize which code to keep. Those keep rules tell R8 to not only keep that code in your app’s final DEX but also retain its original naming.
