### ISSUE TITLE
Serialization of object ObjectIntHashMap is building keySet wrong

### ISSUE THREAD

**Issue by emrosasmob** [EsotericSoftware/kryo#905]
**Describe the bug**
I am using Kryo to store a ObjectIntHashMap.
This Map has keys that were deleted. They are marked as ObjectIntHashMap.REMOVED_KEY.
Before writing the object, if you do a key set iteration the removed keys do not appear.
After writing and read it back with kryo, if you do a key set iteration the removed keys DO appear, and some keys that should appear do not appear.

**To Reproduce**
Run the example in attachment.

**Environment:**
 - Kryo Version: 4.0.0
 - Eclipse Collections: eclipse-collections-10.2.0.jar

**Additional context**
Example in Java file in attachment
[TestIntegerSerialization.zip](https://github.com/EsotericSoftware/kryo/files/9292963/TestIntegerSerialization.zip)
.

**Comment by theigl** [comment]
Since `ObjectIntHashMap` doesn't implement the `Collection` or `Map` interfaces, Kryo falls back to the default serializer, which serializes all fields in the object. In your case, this approach doesn't work.

You will need to implement custom serializers for primitive Eclipse Collections. You can either write something like the built-in [MapSerializer](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/MapSerializer.java) or use a simple serializer, that converts the Eclipse map to a JDK map and serializes the result.
