### ISSUE TITLE
serialize and deserialize get npe

### ISSUE THREAD

**Issue by johnicesea** [EsotericSoftware/kryo#917]
**Describe the bug**

serialize and deserialize get npe

Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:358)
	at com.alibaba.fastjson.JSONObject.put(JSONObject.java:49)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:236)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
	at org.example.SerializeTest.main(SerializeTest.java:45)

**To Reproduce**

        Kryo serializer = new Kryo();

        serializer.setRegistrationRequired(false);
        serializer.setInstantiatorStrategy(new StdInstantiatorStrategy());

        JSONObject data = new JSONObject();
        data.put("a", "b");

        // serialize
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        Output output = new Output(os);

        serializer.writeClassAndObject(output, data);
        output.flush();
        byte[] bytes = os.toByteArray();

        //deserialize
        ByteArrayInputStream is = new ByteArrayInputStream(bytes);
        Input input = new Input(is);

        JSONObject deserialized = (JSONObject) serializer.readClassAndObject(input);
        System.out.println(deserialized);

**Environment:**
 - OS: [MacOs]
 - JDK Version: [8]
 - Kryo Version: [5.3.0]

**Additional context**
maven dependencies

com.alibaba:fastjson:1.2.83_noneautotype
com.esotericsoftware:kryo:5.3.0

**Comment by theigl** [comment]
Kryo is not a perfect replacement for Java serialization. It can serialize most JDK classes and most POJOs you throw at it, but it needs help with certain complex classes.

As you can see from the stacktrace, Kryo currently attempts to use the default `MapSerializer` to serialize your `JsonObject`, because it implements the map interface.

You can try to force Kryo to use the `FieldSerializer` with `kryo.register(JsonObject.class, new FieldSerializer(..))`.

If that doesn't work, you will need to implement a custom serializer.

**Comment by johnicesea** [comment]
force use FieldSerializer works okay，thanks

`serializer.register(JSONObject.class, new FieldSerializer(serializer, JSONObject.class));`
