### ISSUE TITLE
 How do I check for Kyro version in my project?

### ISSUE THREAD

**Issue by Sam-3344** [EsotericSoftware/kryo#941]
**Problem**
I'm trying to run a blink application. I've built a java application that must call the flink application to read the flink states. 
But when I try to fetch the states from flink, I get this error in my java project. 

I get this error 
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 85

After searching this online I found that there could be a Kyro version mismatch between the client & server. How do I check for the version?

**Environment:**
 - OS: [e.g. Ubuntu]
 - JDK Version: [11]
 - Kryo Version: [??]

**Comment by theigl** [comment]
This is difficult to answer because I don't know your setup. One approach would be to get the WAR/JAR file from the server, extract it and look for the kryo.jar file in the packaged dependencies. It should have the version in the file name. Alternatively, you can extract the JAR and look into the packaged pom.xml file.
