### ISSUE TITLE
Occasionally deserialzed object's field has wrong value

### ISSUE THREAD

**Issue by beanww** [EsotericSoftware/kryo#986]
note: This situation occured very occasionally, and I am not sure if it is because of kryo ser/der function, report this just for help

I serialized a List<pojo> to binary, and save binary into redis,
then after some days,  the pojo has no change,  but just recompiled,
and then occasionally, I got binary from redis and deserialize into List<Pojo>, no exception but I found 
the field value of pojo is wrong, just like :
before kryo ser and put into redis:
Pojo{ 
field1: "val1",
field2: null
}
after get from redis and deser by kryo:
Pojo{
field1: null,
field2: "val1"
}
Is it because of kryo or redis or something others, thanks for help!

**To Reproduce**
sorry for can not reproduce

**Environment:**
 - OS: win/linux
 - JDK Version: jdk1.8
 - Kryo Version: 5.0.0-RC1

**Additional context**

**Comment by theigl** [comment]
Are you really using 5.0.0-RC1? If so, please try to upgrade to 5.5.0. There have been many bug fixes since RC1.

**Comment by beanww** [comment]
Yes, we are using 5.0.0-RC1,  
and if we upgrade to 5.5.0, any incompatible change should be notice ? 
as kryo serialize is infrastructre layer, any issue could impact all apps
Thanks!

**Comment by theigl** [comment]
According to the release notes, all later releases of Kryo 5 should be serialization compatible with RC1. But I'm not sure if this is really true in all cases. I took over maintenance of this project with RC5. Since then, all releases have definitely been compatible.

You will have to do careful testing against your existing data, but I'd definitely recommend that you upgrade to the latest release.

**Comment by beanww** [comment]
OK, thanks!
