### ISSUE TITLE
SynchronizedMap can't de-serialized

### ISSUE THREAD

**Issue by mrniko** [EsotericSoftware/kryo#997]
**Describe the bug**
Instance of Collections.synchronizedMap can't be de-serialized properly. Here is the thrown exception.

```
java.lang.NullPointerException: Cannot enter synchronized block because "this.mutex" is null

	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:236)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
```

**To Reproduce**
```java
        Map<String, String> m = new HashMap<>();
        m.put("1", "2");

        Kryo5Codec c = new Kryo5Codec();
        ByteBuf v = c.getValueEncoder().encode(Collections.synchronizedMap(m));
        Map<String, String> map = (Map<String, String>) c.getValueDecoder().decode(v, null);
```

**Environment:**
 - OS: [e.g. Ubuntu]
 - JDK Version: 17
 - Kryo Version: 5.5.0

**Additional context**

**Comment by theigl** [comment]
Kryo doesn't have a built-in serializer for synchronized collections because it is impossible to write a safe serializer for them (i.e. a serializer that doesn't use reflection and doesn't rely on implementation details).

If you want to serialize synchronized and unmodifiable collections, you need to register the corresponding serializers from https://github.com/magro/kryo-serializers.

**Comment by mrniko** [comment]
Can kryo convert them to a regular collections during serializtion?

**Comment by theigl** [comment]
That is not possible, because the underlying collection could be *any* type of collection. It could be a `SortedMap` for instance. In that case you would lose your custom sort order when deserializing it.
